import type { MeetingAnalysis, MeetingIntelligence } from "@/types/analysis"
import jsPDF from "jspdf"

// ─── Type guard ───────────────────────────────────────────────────────────────

function isIntelligence(a: MeetingAnalysis): a is MeetingIntelligence {
  return "blockers" in a
}

// ─── Markdown ─────────────────────────────────────────────────────────────────

export function toMarkdown(analysis: MeetingAnalysis): string {
  const { title, summary, actionItems, decisions, participants } = analysis
  const intel = isIntelligence(analysis) ? analysis : null

  const items = actionItems
    .map(
      (a) =>
        `- [ ] **${a.task}** — ${a.assignee} | Due: ${a.due} | Priority: ${a.priority}${
          a.storyPoints ? ` | ${a.storyPoints}pt` : ""
        }`
    )
    .join("\n")

  const dec = decisions.map((d) => `- ${d}`).join("\n")
  const people = participants.map((p) => `- ${p.name} (${p.role})`).join("\n")

  let md = `# ${title}\n\n## Summary\n${summary}\n\n## Action Items\n${items || "None"}\n\n## Key Decisions\n${dec || "None"}\n\n## Participants\n${people || "None"}\n`

  if (intel?.blockers?.length) {
    const bl = intel.blockers
      .map((b) => `- **[${b.severity}]** ${b.description} — Owner: ${b.owner}`)
      .join("\n")
    md += `\n## Blockers & Risks\n${bl}\n`
  }

  if (intel?.sprintPlan?.length) {
    const sp = intel.sprintPlan
      .map(
        (s) =>
          `### ${s.name} (${s.startDate} → ${s.endDate})\n` +
          `Capacity: ${s.capacity} pts\n` +
          s.goals.map((g) => `- ${g}`).join("\n")
      )
      .join("\n\n")
    md += `\n## Sprint Plan\n${sp}\n`
  }

  if (intel?.followUps?.length) {
    const fu = intel.followUps
      .map(
        (f) =>
          `### Follow-up: ${f.recipient} (${f.channel})\n**Subject:** ${f.subject}\n\n${f.body}`
      )
      .join("\n\n---\n\n")
    md += `\n## Follow-up Drafts\n${fu}\n`
  }

  md += `\n---\n*Generated by Minutely*\n`
  return md
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}

export function downloadMarkdown(analysis: MeetingAnalysis): void {
  const blob = new Blob([toMarkdown(analysis)], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${slug(analysis.title)}.md`
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Sprint CSV ───────────────────────────────────────────────────────────────

export function downloadSprintCSV(analysis: MeetingAnalysis): void {
  if (!isIntelligence(analysis) || !analysis.sprintPlan?.length) return

  const itemById = Object.fromEntries(analysis.actionItems.map((a) => [a.id, a]))

  const rows: string[][] = [
    ["Sprint", "Start", "End", "Capacity (pts)", "Task ID", "Task", "Assignee", "Due", "Priority", "Story Points"],
  ]

  for (const sprint of analysis.sprintPlan) {
    for (const taskId of sprint.tasks) {
      const item = itemById[taskId]
      if (!item) continue
      rows.push([
        sprint.name,
        sprint.startDate,
        sprint.endDate,
        String(sprint.capacity),
        item.id,
        item.task,
        item.assignee,
        item.due,
        item.priority,
        String(item.storyPoints ?? ""),
      ])
    }
  }

  const csv = rows.map((r) => r.map(csvCell).join(",")).join("\n")
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${slug(analysis.title)}-sprint-plan.csv`
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Blockers JSON ────────────────────────────────────────────────────────────

export function downloadBlockersJSON(analysis: MeetingAnalysis): void {
  if (!isIntelligence(analysis) || !analysis.blockers?.length) return

  const payload = {
    meetingTitle: analysis.title,
    exportedAt: new Date().toISOString(),
    blockers: analysis.blockers,
  }

  const blob = new Blob([JSON.stringify(payload, null, 2)], {
    type: "application/json",
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${slug(analysis.title)}-blockers.json`
  a.click()
  URL.revokeObjectURL(url)
}

// ─── PDF ──────────────────────────────────────────────────────────────────────

export function downloadPDF(analysis: MeetingAnalysis): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 20

  const addText = (
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [30, 30, 30]
  ) => {
    doc.setFontSize(size)
    doc.setFont("helvetica", style)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, maxWidth)
    if (y + lines.length * (size * 0.4) > 280) {
      doc.addPage()
      y = 20
    }
    doc.text(lines, margin, y)
    y += lines.length * (size * 0.4) + 2
  }

  const addSection = (title: string) => {
    y += 4
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, pageWidth - margin, y)
    y += 6
    addText(title, 11, "bold", [80, 80, 80])
    y += 1
  }

  const intel = isIntelligence(analysis) ? analysis : null

  // Title block
  addText(analysis.title, 18, "bold", [10, 10, 10])
  y += 2
  addText(
    `Generated by Minutely · ${new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })}${intel ? ` · Mode: ${intel.analysisMode}` : ""}`,
    9,
    "normal",
    [150, 150, 150]
  )
  y += 4

  // Summary
  addSection("SUMMARY")
  addText(analysis.summary, 10)

  // Action Items
  addSection(`ACTION ITEMS (${analysis.actionItems.length})`)
  if (!analysis.actionItems.length) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.actionItems.forEach((item, i) => {
      addText(`${i + 1}. ${item.task}`, 10, "bold")
      addText(
        `   ${item.assignee} · Due: ${item.due} · ${item.priority} priority${
          item.storyPoints ? ` · ${item.storyPoints}pt` : ""
        }`,
        9,
        "normal",
        [100, 100, 100]
      )
      y += 1
    })
  }

  // Blockers (new)
  if (intel?.blockers?.length) {
    addSection(`BLOCKERS & RISKS (${intel.blockers.length})`)
    intel.blockers.forEach((b) => {
      addText(`[${b.severity}] ${b.description}`, 10, "bold")
      addText(`   Owner: ${b.owner}`, 9, "normal", [100, 100, 100])
      addText(`   Resolution: ${b.suggestedResolution}`, 9, "normal", [100, 100, 100])
      y += 1
    })
  }

  // Sprint Plan (new)
  if (intel?.sprintPlan?.length) {
    addSection(`SPRINT PLAN (${intel.sprintPlan.length} sprints)`)
    intel.sprintPlan.forEach((s) => {
      addText(`${s.name} · ${s.startDate} → ${s.endDate} · ${s.capacity}pt capacity`, 10, "bold")
      s.goals.forEach((g) => addText(`   • ${g}`, 9, "normal", [100, 100, 100]))
      y += 1
    })
  }

  // Decisions
  addSection("KEY DECISIONS")
  if (!analysis.decisions.length) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.decisions.forEach((d) => addText(`• ${d}`, 10))
  }

  // Participants
  addSection("PARTICIPANTS")
  if (!analysis.participants.length) {
    addText("None", 10, "normal", [150, 150, 150])
  } else {
    analysis.participants.forEach((p) => addText(`${p.name} — ${p.role}`, 10))
  }

  doc.save(`${slug(analysis.title)}.pdf`)
}

// ─── Notion clipboard ─────────────────────────────────────────────────────────

export function toNotionClipboard(analysis: MeetingAnalysis): string {
  return toMarkdown(analysis)
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function slug(title: string): string {
  return title.replace(/\s+/g, "-").toLowerCase().replace(/[^a-z0-9-]/g, "")
}

function csvCell(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}